### ISSUE TITLE
Hi , I have seen your GitHub and found it interesting.

### ISSUE THREAD

**Issue by ElephantTweakerdeblaterSAK** [mosol1/WindowsSearch#1]
I would like to make some changes to it though, first changing overlay test mode does not help with performance as of the latest updates. Also some PCs don't support scewin. Intel bios tweaks may not work on all. I suggest turning into CLI cmd batch with selectable options as Nvidia silk smoothness should not be touched on the latest drivers. For new people to tweaking I suggest making your ClI drag into Nsudo so everything applies correctly. I noticed that you miss Nsudo. Did you make these tweaks your self and test or no ?

**Comment by ElephantTweakerdeblaterSAK** [comment]
This is not a issue by the way

**Comment by ElephantTweakerdeblaterSAK** [comment]
Only place I could post

**Comment by ElephantTweakerdeblaterSAK** [comment]
I have also noticed that in another repository you use the name VorteX. If you want to name the batch with cli VorteX it would be cool. Also big rookie mistake is that you should be testing every tweak. If not there can be growing amounts of placebo.

**Comment by ElephantTweakerdeblaterSAK** [comment]
I am no longer a public professional PC tweaker but here are some must have changes if ever wanting to go public and make your tweaks faster.

**Comment by ElephantTweakerdeblaterSAK** [comment]
@mosol1

**Comment by mosol1** [comment]
hi

**Comment by mosol1** [comment]
@ElephantTweakerdeblaterSAK 

Do you have a Discord?

**Comment by ElephantTweakerdeblaterSAK** [comment]
No

**Comment by ElephantTweakerdeblaterSAK** [comment]
@mosol1

**Comment by ElephantTweakerdeblaterSAK** [comment]
I am no longer a public tweaker

**Comment by ElephantTweakerdeblaterSAK** [comment]
Can't help you, sadly

**Comment by mosol1** [comment]
Please create one

**Comment by mosol1** [comment]
i have to discuss something

**Comment by mosol1** [comment]
![image](https://github.com/mosol1/WindowsSearch/assets/88799791/630a7814-38c6-41cd-8dd6-6f517b796d74)

**Comment by mosol1** [comment]
Just create a discord real quick i wanna delete this chat

**Comment by ElephantTweakerdeblaterSAK** [comment]
I can't

**Comment by ElephantTweakerdeblaterSAK** [comment]
I'm not allowed

**Comment by mosol1** [comment]
ok, what can you use?

**Comment by ElephantTweakerdeblaterSAK** [comment]
What is this app exactly

**Comment by mosol1** [comment]
Its my Optimization App

**Comment by mosol1** [comment]
its paid

**Comment by ElephantTweakerdeblaterSAK** [comment]
Can't use anything, I just came across your form and liked it

**Comment by mosol1** [comment]
i just store my tweaks here

**Comment by ElephantTweakerdeblaterSAK** [comment]
> its paid

Oh

**Comment by mosol1** [comment]
I didnt want nobody to see this repo

**Comment by ElephantTweakerdeblaterSAK** [comment]
Look, if it's paid , you should test your tweaks more , and discover tweaks.

**Comment by mosol1** [comment]
i wanna delete this chat

**Comment by mosol1** [comment]
oes github have dms?

**Comment by ElephantTweakerdeblaterSAK** [comment]
Read some books , get a feel and learn subjects

**Comment by ElephantTweakerdeblaterSAK** [comment]
> oes github have dms?

No

**Comment by ElephantTweakerdeblaterSAK** [comment]
Do you want to know how I found this repo

**Comment by mosol1** [comment]
ik, im stupid i followed you

**Comment by mosol1** [comment]
did i?

**Comment by ElephantTweakerdeblaterSAK** [comment]
> ik, im stupid i followed you

? , no

**Comment by mosol1** [comment]
then how?

**Comment by ElephantTweakerdeblaterSAK** [comment]
When ???

**Comment by ElephantTweakerdeblaterSAK** [comment]
Don't call your self stupid

**Comment by mosol1** [comment]
bro i cnt be talking here, also i would like you to fix that 
![image](https://github.com/mosol1/WindowsSearch/assets/88799791/f2b40ecf-6d53-451f-83bd-53e316b412ac)

**Comment by mosol1** [comment]
where else can we talk?

**Comment by ElephantTweakerdeblaterSAK** [comment]
Oh okay, well fare well, I can't talk and read boring bordems thing , use capframex and start reading windows books at the library I'm going to start reading windows internals 7th edition, also learn how to discover new tweaks. I will delete the repo after. Stop disabling fault tolerant heap also test and find out why. Aggregate tests by 5 . Use presentMon and xperf

**Comment by ElephantTweakerdeblaterSAK** [comment]
I found your GitHub by searching a Nvidia registry edit into the GitHub

**Comment by ElephantTweakerdeblaterSAK** [comment]
I found this repository

**Comment by ElephantTweakerdeblaterSAK** [comment]
![Uploading Screenshot_20240508-193720.png…]()

**Comment by ElephantTweakerdeblaterSAK** [comment]
@mosol1

**Comment by mosol1** [comment]
yh i also needed someone to go through it and fix some little stuff

**Comment by mosol1** [comment]
i need to delete this issue before more people see the repo

**Comment by ElephantTweakerdeblaterSAK** [comment]
Please learn too.

**Comment by ElephantTweakerdeblaterSAK** [comment]
Okay

**Comment by ElephantTweakerdeblaterSAK** [comment]
I mean test

**Comment by mosol1** [comment]
> Oh okay, well fare well, I can't talk and read boring bordems thing , use capframex and start reading windows books at the library I'm going to start reading windows internals 7th edition, also learn how to discover new tweaks. I will delete the repo after. Stop disabling fault tolerant heap also test and find out why. Aggregate tests by 5 . Use presentMon and xperf

i read sysinternals and some other windows stuff

**Comment by ElephantTweakerdeblaterSAK** [comment]
Not your fault just make sure to go in and become amazing, work.

**Comment by mosol1** [comment]
i m like 1 year expreienced

**Comment by ElephantTweakerdeblaterSAK** [comment]
> > Oh okay, well fare well, I can't talk and read boring bordems thing , use capframex and start reading windows books at the library I'm going to start reading windows internals 7th edition, also learn how to discover new tweaks. I will delete the repo after. Stop disabling fault tolerant heap also test and find out why. Aggregate tests by 5 . Use presentMon and xperf
> 
> i read sysinternals and some other windows stuff

Nice

**Comment by ElephantTweakerdeblaterSAK** [comment]
See you

**Comment by mosol1** [comment]
thats how i made some scripts like dwm enable mmcss

**Comment by mosol1** [comment]
> See you

how are you going to help me fix that tho?

**Comment by mosol1** [comment]
or send your gmail?

**Comment by mosol1** [comment]
email*

**Comment by ElephantTweakerdeblaterSAK** [comment]
I can't publicly tweak.

**Comment by ElephantTweakerdeblaterSAK** [comment]
> thats how i made some scripts like dwm enable mmcss

No

**Comment by ElephantTweakerdeblaterSAK** [comment]
Sorry

**Comment by mosol1** [comment]
oh crap, can we talk in your own repo?
